### ISSUE TITLE
pip install -r requirements.txt throws error

### ISSUE THREAD

**Issue by gotnull** [schollz/poetry-generator#9]
» pip install -r requirements.txt                                                                                    
```waitress (from -r requirements.txt (line 1))
  Using cached waitress-1.0.2-py2.py3-none-any.whl
Collecting pyyaml (from -r requirements.txt (line 2))
  Using cached PyYAML-3.12.tar.gz
Installing collected packages: waitress, pyyaml
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/waitress'
```

**Comment by gotnull** [comment]
Fixed by running ```sudo pip install -r requirements.txt```
